package:
  name: r-scansnv
  version: '0.1'

source:
  git_url: https://github.com/parklab/r-scansnv.git

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - toolchain        # [win]
    - filesystem        # [win]
    - make
    - sed               # [win]
    - coreutils         # [win]
    - zip               # [win]
  host:
    - r-base
    - openblas 0.3.4 ha44fe06_0
  run:
    - r-base
    - openblas 0.3.4 ha44fe06_0

test:
  commands:
    - $R -e "library('scansnv')"           # [not win]
    - "\"%R%\" -e \"library('scansnv')\""  # [win]

about:
  home: https://github.com/parklab/r-scansnv
  summary: Single cell somatic SNV genotyper.
